#docker-compose up -d
spring_boot_work_rep:
  image: spring_boot_work_rep
  links:
    - spring_boot_work_rep_db:mysql
  ports:
    - 8080:80
spring_boot_work_rep_db:
  image : mysql
  environment:
    MYSQL_ROOT_PASSWORD : 123

